config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get :weather, to: "weather#index", as: :weather
  get "weather/forecast", to: "weather#forecast", as: :weather_forecast

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
  # <tt>GET /weather</tt>
  #
  # Shows the form for the user to enter a location.
  def index
  end

  # <tt>GET /weather/forecast?location=[]</tt>
  #
  # Fetches the weather for the requested location and displays it.
  #
  # If for some reason the weather cannot be displayed, the user is returned to the form with an error message.
  #
  # When the location is not found, a 404 is returned and an error message is displayed.
  # When an error occurs while fetching the weather, a 500 is returned and an error message is displayed.
  def forecast
    requested_location = params[:location]
    api = WeatherApi.new(ENV["WEATHER_API_KEY"])
    @weather = api.fetch_weather(requested_location)
  rescue WeatherApi::LocationNotFound
    @error = "Location not found. Please try again."
    render :index, status: :not_found
  rescue WeatherApi::Error
    @error = "An error occurred while fetching the weather. Please try again later."
    render :index, status: :internal_server_error
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weather</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body class="p-4 flex flex-col gap-4">
    <%= yield %>
  </body>
</html>

app/views/weather/forecast.html.erb
<h1 class="text-2xl">Weather for <%= @weather.location.name %></h1>

<p>It's <%= @weather.conditions.text.downcase %> and feels like <%= @weather.conditions.temperature %>ºF outside.</p>

<h2 class="text-xl">Forecast</h2>

<div class="flex gap-4">
  <% @weather.daily_forecasts.each do |forecast| %>
    <div class="flex flex-col border rounded p-2 w-40 items-center">
      <span class="text-sm pb-1"><%= forecast[:date] %></span>
      <img src="<%= forecast[:icon] %>" alt="<%= forecast[:text] %>" class="w-24">
      <div class="flex flex-col items-start">
        <span><%= forecast[:text] %> </span>
        <span>High: <%= forecast[:high] %>ºF</span>
        <span>Low: <%= forecast[:low] %>ºF</span>
      </div>
    </div>
  <% end %>
</div>

<div class="text-xs">
  <p>
    Weather conditions and forecast as of <%= time_tag @weather.as_of do %><%= time_ago_in_words @weather.as_of%><% end %> ago.
  </p>
  <% if @weather.cached? %>
    <p>This data has been cached and may not be up to date.</p>
  <% end %>
</div>

app/views/weather/index.html.erb
<% if @error %>
  <p class="text-red-500"><%= @error %></p>
<% end %>

<%= form_with method: :get, url: weather_forecast_path, class: "flex flex-col gap-4 w-72" do |f| %>
  <%= f.text_field :location, placeholder: "Zip Code or City Name" %>
  <%= f.submit "Look up weather" %>
<% end %>